from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import mysql.connector as mc

class Ui_COFFEECO(object):
    def __init__(self):
        self.conn = None  # Connection object

    def connect_database(self):
        try:
            self.conn = mc.connect(
                host="localhost",
                user="root",
                password="jmps_092902",
                database="db_pyqt5"
            )
            print("Connected to MySQL database successfully!")
        except mc.Error as err:
            print(f"Error connecting to MySQL database: {err}")

    def insert_data(self, flavor, category, stock, sixteen_oz, twenty4_oz, thirty2_oz):
        try:
            cursor = self.conn.cursor()
            sql = "INSERT INTO tbl_cof (Flavor, Category, Stock, 16oz, 24oz, 32oz) VALUES (%s, %s, %s, %s, %s, %s)"
            values = (flavor, category, stock, sixteen_oz, twenty4_oz, thirty2_oz)
            cursor.execute(sql, values)
            self.conn.commit()
            cursor.close()
            print("Data inserted successfully!")
        except mc.Error as err:
            print(f"Error inserting data: {err}")

    def mainWindow(self):
        from Main_Window import Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def collect(self):
        from Main_Window import espresso
        from Main_Window import frappe
        from Main_Window import milkshake
        flavor = str(self.enterproname.text())
        category = str(self.choosecateg.currentText())
        stock = int(self.choosestocks.value())
        sixteen_oz = self.sixteen_oz.isChecked()
        twenty4_oz = self.twenty4_oz.isChecked()
        thirty2_oz = self.thirty2_oz.isChecked()

        if flavor != '' and category != 'Choose Category':
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setWindowTitle("Inserted Value")
            msg.setText("You Inserted the following details:\n"
                        + f'Flavor: {flavor}\n'
                        + f'Category: {category}\n'
                        + f'In Stocks: {stock}\n'
                        + f'16oz: {sixteen_oz}\n'
                        + f'24oz: {twenty4_oz}\n'
                        + f'32oz: {thirty2_oz}'
                        )
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            retval = msg.exec_()

            if retval == QMessageBox.Ok:
                self.connect_database()
                self.insert_data(flavor, category, stock, sixteen_oz, twenty4_oz, thirty2_oz)
            if category == 'Espresso':
                espresso.append(flavor)
            elif category == 'Frappe':
                frappe.append(flavor)
            elif category == 'Milkshake':
                milkshake.append(flavor)
        else:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setWindowTitle("Warning")
            msg.setText("Some details are empty, please complete the details first.")
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            retval = msg.exec_()

    def setupUi(self, COFFEECO):
        COFFEECO.setObjectName("COFFEECO")
        COFFEECO.resize(971, 722)
        COFFEECO.setFixedSize(971,722)
        self.centralwidget = QtWidgets.QWidget(COFFEECO)
        self.centralwidget.setObjectName("centralwidget")
        self.title_frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.title_frame_2.setGeometry(QtCore.QRect(0, 0, 971, 201))
        self.title_frame_2.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.title_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame_2.setObjectName("title_frame_2")
        self.line_2 = QtWidgets.QFrame(self.title_frame_2)
        self.line_2.setGeometry(QtCore.QRect(0, 170, 971, 31))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(0)
        self.line_2.setMidLineWidth(26)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.title_frame = QtWidgets.QFrame(self.title_frame_2)
        self.title_frame.setGeometry(QtCore.QRect(210, 20, 561, 131))
        self.title_frame.setStyleSheet("border-color: rgb(0, 0, 0);\n"
                                       "background-color: rgb(168, 75, 43);")
        self.title_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.title_frame.setLineWidth(4)
        self.title_frame.setObjectName("title_frame")
        self.business_logo = QtWidgets.QLabel(self.title_frame)
        self.business_logo.setGeometry(QtCore.QRect(20, 10, 111, 111))
        self.business_logo.setText("")
        self.business_logo.setPixmap(QtGui.QPixmap("business_logo.png"))
        self.business_logo.setScaledContents(True)
        self.business_logo.setObjectName("business_logo")
        self.business_title = QtWidgets.QLabel(self.title_frame)
        self.business_title.setGeometry(QtCore.QRect(140, 20, 411, 61))
        font = QtGui.QFont()
        font.setFamily("RomanC")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.business_title.setFont(font)
        self.business_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.business_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.business_title.setObjectName("business_title")
        self.business_subtitle = QtWidgets.QLabel(self.title_frame)
        self.business_subtitle.setGeometry(QtCore.QRect(140, 80, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.business_subtitle.setFont(font)
        self.business_subtitle.setObjectName("business_subtitle")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(0, 200, 981, 541))
        self.frame_7.setStyleSheet("background-color: rgb(99, 43, 5);\n"
                                   "")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.insert_button1 = QtWidgets.QPushButton(self.frame_7, clicked=lambda: self.collect())
        self.insert_button1.setGeometry(QtCore.QRect(530, 470, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.insert_button1.setFont(font)
        self.insert_button1.setStyleSheet("background-color: rgb(255, 85, 0);\n"
                                          "font: 11pt \"Rockwell\";")
        self.insert_button1.setAutoDefault(True)
        self.insert_button1.setDefault(False)
        self.insert_button1.setFlat(False)
        self.insert_button1.setObjectName("insert_button1")
        self.cancel_button = QtWidgets.QPushButton(self.frame_7)
        self.cancel_button.setGeometry(QtCore.QRect(400, 470, 81, 31))
        self.cancel_button.clicked.connect(self.mainWindow)
        self.cancel_button.clicked.connect(COFFEECO.close)

        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("background-color: rgb(162, 162, 162);\n"
                                         "font: 11pt \"Rockwell\";")
        self.cancel_button.setAutoDefault(True)
        self.cancel_button.setDefault(False)
        self.cancel_button.setFlat(False)
        self.cancel_button.setObjectName("cancel_button")
        self.details_groupbox = QtWidgets.QGroupBox(self.frame_7)
        self.details_groupbox.setGeometry(QtCore.QRect(30, 40, 911, 401))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.details_groupbox.setFont(font)
        self.details_groupbox.setMouseTracking(False)
        self.details_groupbox.setStyleSheet("background-color: rgb(168, 75, 43);\n"
                                            "")
        self.details_groupbox.setFlat(False)
        self.details_groupbox.setCheckable(False)
        self.details_groupbox.setObjectName("details_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.details_groupbox)
        self.verticalLayout.setContentsMargins(6, -1, 6, 8)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(self.details_groupbox)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.product_name = QtWidgets.QLabel(self.frame_8)
        self.product_name.setGeometry(QtCore.QRect(220, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.product_name.setFont(font)
        self.product_name.setObjectName("product_name")
        self.enterproname = QtWidgets.QLineEdit(self.frame_8)
        self.enterproname.setGeometry(QtCore.QRect(370, 20, 320, 30))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(16)
        self.enterproname.setFont(font)
        self.enterproname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterproname.setText("")
        self.enterproname.setClearButtonEnabled(True)
        self.enterproname.setObjectName("enterproname")
        self.category = QtWidgets.QLabel(self.frame_8)
        self.category.setGeometry(QtCore.QRect(220, 90, 141, 41))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.category.setFont(font)
        self.category.setObjectName("category")
        self.choosecateg = QtWidgets.QComboBox(self.frame_8)
        self.choosecateg.setGeometry(QtCore.QRect(370, 90, 320, 30))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(14)
        self.choosecateg.setFont(font)
        self.choosecateg.setMouseTracking(True)
        self.choosecateg.setAutoFillBackground(False)
        self.choosecateg.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                       "")
        self.choosecateg.setEditable(True)
        self.choosecateg.setMaxCount(2147483645)
        self.choosecateg.setMinimumContentsLength(3)
        self.choosecateg.setObjectName("choosecateg")
        self.choosecateg.addItem("")
        self.choosecateg.addItem("")
        self.choosecateg.addItem("")
        self.choosecateg.addItem("")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setGeometry(QtCore.QRect(220, 150, 141, 41))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.choosestocks = QtWidgets.QSpinBox(self.frame_8)
        self.choosestocks.setGeometry(QtCore.QRect(370, 150, 320, 30))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(16)
        font.setKerning(True)
        self.choosestocks.setFont(font)
        self.choosestocks.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.choosestocks.setMaximum(500)
        self.choosestocks.setSingleStep(1)
        self.choosestocks.setObjectName("choosestocks")
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_4 = QtWidgets.QFrame(self.details_groupbox)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setGeometry(QtCore.QRect(220, 20, 161, 71))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setGeometry(QtCore.QRect(430, 70, 153, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.thirty2_oz = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        self.thirty2_oz.setFont(font)
        self.thirty2_oz.setObjectName("thirty2_oz")
        self.verticalLayout_3.addWidget(self.thirty2_oz)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(440, 30, 151, 63))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.sixteen_oz = QtWidgets.QCheckBox(self.frame_2)
        self.sixteen_oz.setGeometry(QtCore.QRect(0, -12, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        self.sixteen_oz.setFont(font)
        self.sixteen_oz.setObjectName("sixteen_oz")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(0, 30, 151, 31))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.twenty4_oz = QtWidgets.QCheckBox(self.frame_6)
        self.twenty4_oz.setGeometry(QtCore.QRect(0, 0, 133, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        self.twenty4_oz.setFont(font)
        self.twenty4_oz.setObjectName("twenty4_oz")
        self.frame.raise_()
        self.frame_10.raise_()
        self.frame_2.raise_()
        self.verticalLayout.addWidget(self.frame_4)
        COFFEECO.setCentralWidget(self.centralwidget)

        self.retranslateUi(COFFEECO)
        QtCore.QMetaObject.connectSlotsByName(COFFEECO)

    def retranslateUi(self, COFFEECO):
        _translate = QtCore.QCoreApplication.translate
        COFFEECO.setWindowTitle(_translate("COFFEECO", "MainWindow"))
        self.business_title.setText(_translate("COFFEECO", "COFFEE.CO "))
        self.business_subtitle.setText(
            _translate("COFFEECO", "A PROJECT BY: BURATO, FAJARDO, SEGUNDO, SIBAYAN, VILLANUEVA"))
        self.insert_button1.setText(_translate("COFFEECO", "Insert"))
        self.cancel_button.setText(_translate("COFFEECO", "Back"))
        self.details_groupbox.setTitle(_translate("COFFEECO", "Please insert details below."))
        self.product_name.setText(_translate("COFFEECO", "Flavour:"))
        self.category.setText(_translate("COFFEECO", "Category:"))
        self.choosecateg.setItemText(0, _translate("COFFEECO", "Choose Category"))
        self.choosecateg.setItemText(1, _translate("COFFEECO", "Espresso"))
        self.choosecateg.setItemText(2, _translate("COFFEECO", "Frappe"))
        self.choosecateg.setItemText(3, _translate("COFFEECO", "Milkshake"))
        self.label_5.setText(_translate("COFFEECO", "In Stocks:"))
        self.label_3.setText(_translate("COFFEECO", "Sizes Available:"))
        self.thirty2_oz.setText(_translate("COFFEECO", "32oz ($89)"))
        self.sixteen_oz.setText(_translate("COFFEECO", "16oz ($49)"))
        self.twenty4_oz.setText(_translate("COFFEECO", "24oz ($69)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    COFFEECO = QtWidgets.QMainWindow()
    COFFEECO.setWindowIcon(QtGui.QIcon('icon_logo.png'))
    ui = Ui_COFFEECO()
    ui.setupUi(COFFEECO)
    COFFEECO.show()
    sys.exit(app.exec_())
